### ISSUE TITLE
Need recipes for snacks

### ISSUE THREAD

**Issue by jbkieffer** [kulibraries/20181130-gh-contribute#1]
<a href="https://github.com/jbkieffer"><img src="https://avatars2.githubusercontent.com/u/23423968?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jbkieffer](https://github.com/jbkieffer)**
_Mon Nov 19 22:13:01 2018_
_Originally opened as https://github.com/jbkieffer/github-training/issues/1_

----

Please add recipes for snacks for our party in a file called `snack-recipes.md`.

**Comment by ljohnson18** [comment]
I'll work on this.
