### ISSUE TITLE
Need more cocktail recipes

### ISSUE THREAD

**Issue by jbkieffer** [kulibraries/20181130-gh-contribute#2]
<a href="https://github.com/jbkieffer"><img src="https://avatars2.githubusercontent.com/u/23423968?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jbkieffer](https://github.com/jbkieffer)**
_Mon Nov 19 22:13:52 2018_
_Originally opened as https://github.com/jbkieffer/github-training/issues/2_

----

Please add one or more cocktail recipes to the file `cocktail-recipes.md`.

**Comment by orobecca** [comment]
I can find some more cocktail recipes.
