### ISSUE TITLE
Party needs music playlist

### ISSUE THREAD

**Issue by jbkieffer** [kulibraries/20181130-gh-contribute#3]
<a href="https://github.com/jbkieffer"><img src="https://avatars2.githubusercontent.com/u/23423968?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jbkieffer](https://github.com/jbkieffer)**
_Mon Nov 19 22:15:52 2018_
_Originally opened as https://github.com/jbkieffer/github-training/issues/3_

----

Please add a playlist of music for this party in a file called `music-playlist.md`.

**Comment by rovinghistorian** [comment]
I'm all over this.

**Comment by ppprudh** [comment]
Lots of choice
