### ISSUE TITLE
Add a shopping list

### ISSUE THREAD

**Issue by jbkieffer** [kulibraries/20181130-gh-contribute#4]
<a href="https://github.com/jbkieffer"><img src="https://avatars2.githubusercontent.com/u/23423968?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jbkieffer](https://github.com/jbkieffer)**
_Mon Nov 19 22:18:33 2018_
_Originally opened as https://github.com/jbkieffer/github-training/issues/4_

----

Please make a shopping list for supplies for this party using the file name `shopping-list.md`.
You can create a checklist in Markdown using the following syntax:
`- [ ] item`
`- [ ] item`
`- [ ] item`

**Comment by christinklez** [comment]
You got it! I will work on this.
