### ISSUE TITLE
Games for our party

### ISSUE THREAD

**Issue by jbkieffer** [kulibraries/20181130-gh-contribute#5]
<a href="https://github.com/jbkieffer"><img src="https://avatars2.githubusercontent.com/u/23423968?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jbkieffer](https://github.com/jbkieffer)**
_Mon Nov 19 22:29:01 2018_
_Originally opened as https://github.com/jbkieffer/github-training/issues/5_

----

Please make a list of games we can play at the party. Use the file name `games.md`.
If you like, you can separate the list into sections by type of game or game audience.

**Comment by hjblack** [comment]
I have a great resource for party games. I can create a list for us
