### ISSUE TITLE
Suggest decorations

### ISSUE THREAD

**Issue by jbkieffer** [kulibraries/20181130-gh-contribute#6]
<a href="https://github.com/jbkieffer"><img src="https://avatars2.githubusercontent.com/u/23423968?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jbkieffer](https://github.com/jbkieffer)**
_Mon Nov 19 22:32:47 2018_
_Originally opened as https://github.com/jbkieffer/github-training/issues/6_

----

Please make suggestions for decorations for our party using the file name `decorations.md`.

**Comment by Tammoo** [comment]
I'll bring the decorations!
